services:
  app:
    build: .
    ports:
      - "4000:4000"
    depends_on:
      - mongo
    environment:
      - PORT=4000
    container_name: request-monitor-backend-app
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  mongo:
    image: mongo:5
    container_name: request-monitor-mongo
    ports:
      - "37017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
