version: 2.1
orbs:
  node: circleci/node@5
jobs:
  build-node:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run build
      - store_artifacts:
          path: build
          destination: node-build
  test-node:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run TypeScript Tests
          command: ./node_modules/.bin/mocha ./tests/unit/**/*.spec.ts --require ts-node/register --config .mocharc.json
workflows:
  build-and-test:
    jobs:
      - test-node
      - build-node:
          requires:
            - test-node
