version: 2.1

executors:
  docker-executor:
    docker:
      - image: docker:stable
    working_directory: ~/project

jobs:
  build:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.8
      - run:
          name: Build Docker Image
          command: |
            docker build -t custom-docker-image:latest .

  test:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.8
      - run:
          name: Use Docker Image for Testing
          command: |
            docker run --rm \
              -v $(pwd):/usr/src/app \
              -w /usr/src/app \
              custom-docker-image:latest \
              sh -c "npm install && npm test"

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
