version: 2.1

jobs:
  build:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - run:
          name: Build Docker Image
          command: docker build -t custom-docker-image .

  test:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - run:
          name: Run Tests in Docker
          command: |
            docker run --rm \
              -v $(pwd):/app \
              -w /app custom-docker-image \
              sh -c "npm install && npm test"

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
