version: 2.1

jobs:
  build:
    docker:
      - image: custom-docker-image:latest
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build the project
          command: |
            npm install
            npm run build

  test:
    docker:
      - image: custom-docker-image:latest
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Run Unit Tests
          command: |
            npm install
            npm test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
