version: 2.1
orbs:
  node: circleci/node@5
jobs:
  build-node:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run build
      - store_artifacts:
          path: build
          destination: node-build
  test-node:
    executor: node/default
    environment:
      NODE_ENV: development
      APP_PORT: 4000
      APP_HOST: localhost
      DB_DRIVER: mongodb
      MONGODB_PORT: 27017
      MONGODB_DB: request-monitor
      PING_INTERVAL: 1

    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Add typescript
          command: npm install -g @types/chai-as-promised @types/node @typescript-eslint/eslint-plugin @typescript-eslint/parser chai chai-as-promised eslint eslint-config-airbnb-base eslint-plugin-import mocha nyc ts-node typescript
      - run:
          name: Run TypeScript Tests
          # Make sure the build is updated
          # @todo: configure circle-ci to interpret ".ts" extensions
          command:  npx mocha ./tests/unit/**/*.spec.ts --require ts-node/register --config .mocharc.json
workflows:
  build-and-test:
    jobs:
      - test-node
      - build-node:
          requires:
            - test-node
